dataset:
  base_path: archive/data
  columns:
    answer: Answer
    extracted_answer: extracted_answer
    id: ID
    problem: Problem
    reasoning_trace: model_completion
    solution: Solution
  name: aime2024
  raw_file: aime_2024_completions_updated.csv
evaluation:
  metrics:
  - accuracy
  - improvement_rate
  - wrong_to_right_percentage
  tolerance: 0.01
imports:
- configs/models/fireworks.yaml
- configs/summarization/default.yaml
logging:
  console_output: true
  level: INFO
  log_file: true
  save_path: logs
model:
  name: deepseek_r1
output:
  results_path: results/recursive_refinement
  save_format: json
  visualizations: true
pipeline:
  batch_size: 4
  confidence_threshold: 0.8
  continuation_prompt: Based on the summary of your previous reasoning, please continue
    solving the problem. Focus specifically on addressing the issues identified in
    the summary.
  early_stopping: true
  evaluation_prompt: Evaluate the above reasoning and answer. Is it correct? If there
    are errors, what are they? Should the reasoning be refined further?
  max_iterations: 3
  name: recursive_refinement
  save_intermediates: true
  synthesis_prompt: Based on all the iterations of reasoning so far, synthesize a
    final answer to the problem.
  type: recursive
reasoning:
  continuation_phrases:
  - Let me think more about this.
  - Actually, I should reconsider my approach.
  - Let me analyze this further.
  - Let me double-check this calculation.
  - I need to think about this from another angle.
  - Let me explore an alternative solution method.
  - I should verify these results with another approach.
  - Let me ensure the reasoning so far is correct.
  - Let me consider if there are any edge cases.
  - I'll try a different way to solve this problem.
  max_extensions: 10
  target_token_count: 2000
  think_tag: true
reasoning_model:
  api_base: https://api.fireworks.ai/inference/v1
  api_type: fireworks
  frequency_penalty: 0.0
  max_tokens: 2000
  model_id: accounts/fireworks/models/deepseek-r1
  name: deepseek-r1
  presence_penalty: 0.0
  retries: 3
  retry_delay: 2
  temperature: 0.7
  timeout: 30
  top_k: 40
  top_p: 1.0
recursive:
  refine_errors_only: true
  track_confidence: true
  use_summarize_tags: false
  use_think_tags: true
summarization:
  external_summary:
    max_tokens: 1000
    prompt: error_focused
    strategy: error_focused
    temperature: 0.5
  max_tokens: 1000
  method: external
  prompt: error_focused
  strategy: error_focused
  temperature: 0.5
summarization_model:
  api_base: https://api.fireworks.ai/inference/v1
  api_type: fireworks
  frequency_penalty: 0.0
  max_tokens: 1000
  model_id: accounts/fireworks/models/deepseek-r1
  name: deepseek-r1
  presence_penalty: 0.0
  retries: 3
  retry_delay: 2
  temperature: 0.5
  timeout: 30
  top_k: 40
  top_p: 1.0
