# Default configuration for summarization

summarization:
  # General settings
  method: self  # Options: self, external
  max_tokens: 1000
  temperature: 0.5
  
  # Strategy configuration
  strategy: default  # Options: default, concise, error_focused, key_steps
  prompt: default    # Options: default, concise, error_focused, key_steps
  
  # Self-summarization specific settings
  self_summary:
    strategy: default
    prompt: default
    max_tokens: 1000
    temperature: 0.7
  
  # External summarization specific settings
  external_summary:
    strategy: default
    prompt: default
    max_tokens: 1000
    temperature: 0.5
    model_name: gpt4o  # Model to use for external summarization