# Multiple choice prompts
gpqa_mc:
  template: |
    {question}
    
    Please solve this multiple-choice problem step by step. First, wrap your entire reasoning process in <think> and </think> tags. After analyzing all options, provide your final answer in \boxed{} format using the letter (A, B, C, or D) of the correct choice.
    
    <instructions>
    1. Begin your response with "<think>"
    2. Show all your calculations and reasoning steps in detail
    3. Evaluate each answer choice carefully
    4. End your thinking with "</think>"
    5. Finally, provide your answer as \boxed{X} where X is the letter of the correct choice (A, B, C, or D)
    </instructions> 